import { useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useGetAllBreedsQuery, useGetDogsByBreedMutation, useGetBreedsImagesMutation } from '../services/api'
import { Message } from '../services/dogType'


const Home: NextPage = () => {
  const {data, error, isLoading} = useGetAllBreedsQuery()
  const [getBreed, {data: subBreedData }] = useGetDogsByBreedMutation() 
  const [breedImage, subBreedImage, {data: breedImageData}] = useGetBreedsImagesMutation()

  useEffect(() => {
   if (subBreedData )
      console.log(subBreedData)
  }, [subBreedData])
  
  useEffect(() => {
    if(breedImageData)
    console.log(breedImageData)
   
  }, [breedImageData])
  
 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <main className={styles.main}>
        {error? (<p>Error wa o</p>) : isLoading? ( <p>E dey load o</p> ) :data? (
       <select onChange={e => getBreed(e.target.value)} className={styles.select} >
         <option value="" >Please select a dog Breed</option>
        {Object.keys(data?.message as Message).map((item, index) => {
          return <option key={index} >{item}</option>
          
        })}
         </select>
      ) : null }
          
         {subBreedData && subBreedData?.message?.length > 0 ?

           <div>
            <p>Sub breed</p>
         <select className={styles.select}>
         
           {subBreedData?.message.map((item, index) => {
            return <option>{item}</option>
           })}
          
         </select>
         </div>
         : null
         }

         {/* <div>
         {breedImage? && subBreedImage?  
         ? <Image src={breedImageData}>
          
          : null}
          
         </div> */}
      </main>
      
        
      
    </div>
  )
}

export default Home
